### ISSUE TITLE
Inference on local video file

### ISSUE THREAD

**Issue by aakash-chakraborty1995** [kschlegel/OAK-HumanPoseEstimation#3]
I have tried the view_video.py with proper flags but it is looking for camera. How to get past that and process local video file?

**Comment by kschlegel** [comment]
How are you trying to run it, what exactly are your command line arguments? Using something like
`python view_video.py --video PATH_TO_VIDEO_FILE`
you should be able to run it on a local video file

**Comment by aakash-chakraborty1995** [comment]
python view_video.py -m openpose1 -sh 8 --num_inference_threads 2 --nce_per_inference_thread 2 -d OpenPose --detection_threshold 30 --num_paf_samples 10 --min_paf_score_th 2 --paf_sample_th 4 --video path_to_local_video_file

I have tried this command and getting this error:
 line 50, in main
    with dai.Device(
RuntimeError: No available devices

**Comment by aakash-chakraborty1995** [comment]
Every time it is looking for a OAK-D camera , it seems.

**Comment by kschlegel** [comment]
You always need an oak device to run this, as the models are evaluated on the device not your computer. The `--video` argument only allows you to change the data source from the live camera feed to a local video file (so that you have reproducible results which you wouldn't get from a live stream). That local file is then transferred to the camera to evaluate the model on the video file.
